# -*- coding: utf-8 -*-
"""Enrichment content (verified via research workflow)."""

HERO_STATS = [('100%', 'мирового рынка EUV-литографии контролирует одна ASML', 'chip', 'chips'), ('35,66 ЭБ', 'данных прошло через амстердамский узел AMS-IX за 2025 год', 'cloud', 'data'), ('~$674 млрд', 'пиковая капитализация ASML — рекорд в истории Европы (2026)', 'spark', 'chips'), ('€32,7 млрд', 'выручка ASML за 2025 год (чистая прибыль €9,6 млрд)', 'euro', 'chips'), ('€615 млн', 'госфинансирование квантовой программы Quantum Delta NL (Делфт)', 'atom', 'ai'), ('>110 млрд', 'полупроводниковых изделий в год отгружает Nexperia из Неймегена', 'globe', 'chips')]
DID_YOU_KNOW = [('Глаже атома', 'Зеркала внутри EUV-машины ASML полирует немецкая Zeiss — это самые гладкие макрообъекты в истории. Увеличь такое зеркало до размеров Германии, и самая высокая «гора» на нём была бы всего около 0,1 мм.', 'spark', 'chips'), ('Плазма горячее Солнца', 'Чтобы получить ультрафиолет с длиной волны 13,5 нм, лазер разбивает капли олова 50 000 раз в секунду, создавая плазму около 220 000 °C — почти в 40 раз горячее поверхности Солнца.', 'bolt', 'chips'), ('Python родом из Амстердама', 'Главный язык data science и ИИ создал Гвидо ван Россум в институте CWI на Amsterdam Science Park в декабре 1989 года — на том же кампусе, где вырос один из крупнейших интернет-узлов мира AMS-IX.', 'globe', 'data'), ('Серверы греют помидоры', 'На площадке Agriport A7 в Мидденмеере остаточное тепло и CO2 дата-центров идут по сетям ECW Energy в крупнейший в Европе тепличный кластер — цифровые «отходы» буквально превращаются в томаты и перцы.', 'cloud', 'ai')]
TIMELINE = [('1984', 'Основание ASML', 'Philips и ASM International создают совместное предприятие ASM Lithography (позже переехавшее в Велдховен) — будущего монополиста в EUV-литографии.', 'chips'), ('2003', 'High Tech Campus Eindhoven', 'Бывший исследовательский кампус Philips открывается для сторонних компаний; сегодня это 300+ фирм и 12 500+ исследователей на одном «самом умном квадратном километре Европы».', 'chips'), ('2006', 'Выделение NXP из Philips', 'Полупроводниковое подразделение Philips становится самостоятельной NXP Semiconductors с ключевой площадкой в Неймегене (рядом Nexperia и Ampleon).', 'chips'), ('2015', 'Основание QuTech в Делфте', 'TU Delft и TNO формально учреждают квантовый институт QuTech (статус «Национальной иконы» получен годом ранее), делая Делфт мировым центром квантовых вычислений.', 'ai'), ('2016', 'Google приходит в Эмсхавен', 'Google вкладывает около €600 млн в дата-центр на севере страны; охлаждение — переработанная промышленная вода по 28-км трубопроводу, питание — ветер.', 'data'), ('2023', 'Экспортный контроль и EU Chips Act', 'Под давлением США Гаага с 1 сентября вводит ограничения на DUV-машины ASML; в сентябре вступает в силу European Chips Act (€43+ млрд, цель 20% к 2030).', 'chips'), ('2025', 'Государство берёт Nexperia под контроль', '13 октября Гаага впервые применяет закон 1952 года и отстраняет китайского гендиректора Nexperia; Пекин блокирует экспорт, под угрозой останова — весь автопром ЕС.', 'chips'), ('2026', 'ASML — рекорд Европы', 'На волне ИИ-бума капитализация ASML в моменте достигает ~$674 млрд — больше, чем когда-либо стоила любая европейская публичная компания.', 'chips')]
SUPPLY_CHAIN = [('1. Литография — «станок»', 'ASML (Нидерланды) — единственный поставщик EUV на всю планету', 'Верхушка пирамиды: без машины из Велдховена физически не работает ни один следующий этаж для передовых узлов.', 'spark'), ('2. Производство пластин', 'TSMC (~90% передовых чипов), Samsung, Intel', 'Тайваньские и корейские фабрики печатают кремний, но только на литографах ASML — рычаг в руках Нидерландов.', 'chip'), ('3. Дизайн (fabless)', 'Apple, Nvidia, Qualcomm — рисуют схемы, своих заводов не имеют', 'Даже гиганты-дизайнеры зависят от первого этажа: их чипы нельзя изготовить без нидерландского оборудования.', 'atom'), ('4. Устройства', 'Смартфоны, серверы ИИ, автомобили', 'Замыкающее звено: сюда же встроены автомобильные и IoT-чипы NXP и Nexperia из Неймегена.', 'globe')]
GEOPOLITICS = {'lead': 'Крошечные Нидерланды оказались прямо на линии фронта чиповой войны США и Китая: Гаага держит рычаг над передовой литографией, а Пекин отвечает контролем над критическим сырьём.', 'points': [('Ноль EUV для Китая', 'Ни один EUV-литограф никогда не был отгружен в Китай. Ещё в 2019 году США убедили нидерландского премьера не продлевать экспортную лицензию ASML — до первой физической поставки; с тех пор EUV под полным запретом.', 'globe'), ('Треть бизнеса под ударом', 'Китай оставался одним из крупнейших рынков ASML: ~36% выручки в 2024-м и 33% в 2025-м. Из-за экспортных ограничений компания прогнозирует падение примерно до 20% в 2026 году — коммерция против геополитики.', 'euro'), ('Ответ сырьём', 'С июля 2023 года Китай ввёл лицензии на экспорт галлия и германия, в апреле 2025-го добавил семь редкоземельных металлов. Пекин контролирует около 98% мирового производства галлия — асимметричное сдерживание.', 'drop'), ('Кейс Nexperia', '13 октября 2025 года Гаага впервые применила закон 1952 года и взяла под контроль Nexperia (Неймеген, с 2019 у китайской Wingtech). Китай заблокировал экспорт — VW, Honda, Ford и Mercedes предупредили об остановке конвейеров; хрупкое перемирие достигнуто в ноябре 2025-го.', 'chip')]}
OUTLOOK = {'lead': 'Нидерланды пытаются повторить «фокус ASML» и в новых гонках — от High-NA EUV до квантового интернета, но главный барьер роста уже не технологии, а физический дефицит электросети.', 'points': [('High-NA EUV пошёл в серию', 'Новейший литограф ASML High-NA (EXE-серия) стоит около $380 млн (≈€350 млн) и весит как два самолёта. В декабре 2025 года Intel первой вышла на серийное производство логики на этой технологии (процессоры Panther Lake).', 'chip'), ('Ставка на кванты', 'QuTech (TU Delft + TNO) и программа Quantum Delta NL (€615 млн из Национального фонда роста) метят в европейскую столицу квантовых вычислений — с партнёрами Microsoft и Intel и первым «городским» квантовым каналом Делфт-Гаага.', 'atom'), ('Узкое горлышко — электросеть', 'Рост ИИ и дата-центров упирается не в инновации, а в дефицит мощностей: очередь оператора TenneT — десятки ГВт заявок, Амстердам ввёл мораторий на новые дата-центры, а свободных мощностей в части Северной Голландии не будет примерно до 2035 года.', 'bolt')]}
ZONE_NUGGETS = {'asml': 'Один EUV-литограф — это ~100 000 деталей от ~5 000 поставщиков в 60 странах.', 'htc': 'Эйндховен — самый изобретательный город планеты: 22,6 патента на 10 000 жителей.', 'nijmegen': 'Одна только Nexperia отгружает отсюда более 110 млрд изделий в год.', 'amsterdam': 'Через узел AMS-IX здесь в 2025 году прошло 35,66 эксабайта данных.', 'eemshaven': 'Google охлаждает ЦОД не питьевой, а переработанной канальной водой (28-км труба).', 'agriport': 'Тепло и CO₂ дата-центров идут в крупнейший тепличный кластер Европы.', 'delft': 'В 2024 году QuTech впервые связал квантовой запутанностью процессоры в двух городах.'}
SOURCES = ['https://www.cnbc.com/2022/03/23/inside-asml-the-company-advanced-chipmakers-use-for-euv-lithography.html', 'https://companiesmarketcap.com/asml/marketcap/', 'https://www.asml.com/en/news/press-releases/2026/q4-2025-financial-results', 'https://www.cnbc.com/2024/01/02/asml-blocked-from-exporting-some-critical-chipmaking-tools-to-china.html', 'https://www.caixinglobal.com/2026-01-29/asml-expects-china-revenue-drop-following-backlog-fueled-surge-102409285.html', 'https://digital-strategy.ec.europa.eu/en/policies/european-chips-act', 'https://www.csis.org/analysis/beyond-rare-earths-chinas-growing-threat-gallium-supply-chains', 'https://www.cnbc.com/2025/10/13/dutch-government-takes-control-of-chinese-owned-chipmaker-nexperia.html', 'https://www.aljazeera.com/news/2025/10/14/why-has-dutch-government-taken-control-of-china-owned-chipmaker-nexperia', 'https://www.euronews.com/business/2025/11/10/nexperia-cleared-to-resume-civilian-chip-shipments-vital-to-european-car-production', 'https://www.asml.com/en/technology/lithography-principles/lenses-and-mirrors', 'https://www.asml.com/en/technology/lithography-principles/light-and-lasers', 'https://www.zeiss.com/semiconductor-manufacturing-technology/euv-lithography.html', 'https://www.tomshardware.com/tech-industry/manufacturing/asmls-high-na-chipmaking-tool-will-cost-dollar380-million', 'https://www.tomshardware.com/tech-industry/asml-beocmes-europes-most-valuable-company-ever-as-analysts-bet-on-higher-euv-output', 'https://www.hollandhightech.nl/en/news-calendar/news/brainport-eindhoven-once-again-a-top-region-for-patents', 'https://www.ams-ix.net/ams/news/ams-ix-hits-new-traffic-peak-at-15-terabit-per-second', 'https://blog.google/inside-google/infrastructure/a-sustainable-solution-helped-a-small-town-cool-its-data-center/', 'https://www.agriporta7.nl/agriport-datacenter-area/', 'https://qutech.nl/2024/10/30/a-rudimentary-quantum-network-link-between-dutch-cities/', 'https://www.nexperia.com/about', 'https://www.cwi.nl/en/news/25-years-of-python-at-cwi/', 'https://www.government.nl/latest/news/2024/03/28/the-netherlands-to-invest-%E2%82%AC2.5-billion-to-strengthen-business-climate-for-chip-industry-in-brainport-eindhoven', 'https://quantumdelta.nl/']

# Short details for the horizontal timeline cards (override)
TIMELINE = [
    ("1984", "Основание ASML", "СП Philips и ASM International в Велдховене.", "chips"),
    ("2003", "High Tech Campus", "Кампус Philips открывается для всех компаний.", "chips"),
    ("2006", "Выделение NXP", "Чипы Philips становятся отдельной компанией.", "chips"),
    ("2015", "QuTech в Делфте", "Рождение мирового центра квантовых вычислений.", "ai"),
    ("2016", "Google в Эмсхавене", "Первый ЦОД Google в континентальной Европе.", "data"),
    ("2023", "Экспортный контроль", "Ограничения на DUV и старт EU Chips Act.", "chips"),
    ("2025", "Госконтроль над Nexperia", "Гаага впервые берёт чип-завод под контроль.", "chips"),
    ("2026", "ASML — рекорд Европы", "Капитализация ~$674 млрд — рекорд континента.", "chips"),
]
