import Foundation

/// The configuration tor is started with, written once per session.
///
/// Ported wholesale from the Android build, including the reasoning, because
/// none of it was Android-specific:
///
///   - tor is started **once**, with every transport declared, so changing
///     route later is a control-port command rather than a restart.
///   - `AvoidDiskWrites` is deliberately absent. What it spares tor from
///     writing promptly is exactly what the next connect needs: the consensus
///     and descriptors it just fetched.
///   - Padding stays on. Mobile Tor apps routinely turn it down for battery;
///     traffic-shape analysis is what it is there to frustrate, and a desktop
///     has no battery excuse at all.
///   - `AutomapHostsOnResolve` gives tor's DNS a virtual address it remembers,
///     so the tunnel can recover the hostname when the connection follows.
///     Without it a transparent proxy resolves at the exit and connects by raw
///     address, which breaks everything behind a CDN.
///
/// The one macOS difference is that SOCKS and control are unix sockets in the
/// container rather than loopback ports, so nothing else on the machine can
/// reach either.
enum Torrc {

    static let virtualNetworkV4 = "10.192.0.0/10"
    static let virtualNetworkV6 = "[FC00::]/7"

    struct Session {
        var dataDirectory: String
        var socksSocket: String
        /// Loopback listeners for the system-proxy mode: SOCKS for what
        /// speaks it, HTTP CONNECT for everything that honours a web proxy.
        var socksPort: Int
        var httpPort: Int
        var controlSocket: String
        var cookieFile: String
        var dnsPort: Int
        /// Transport name to the loopback port its listener is on.
        var plugins: [String: Int]
        var opening: (transport: Transport, bridges: [BridgeLine])?
        var geoipDirectory: String?
    }

    static func build(_ session: Session) -> String {
        var out: [String] = []
        out.append("# Generated by Veil. Rewritten whenever the tunnel starts.")
        out.append("")

        out.append("# --- Where tor keeps what it knows -------------------------------")
        out.append("DataDirectory \(session.dataDirectory)")
        if let geoip = session.geoipDirectory {
            out.append("GeoIPFile \(geoip)/geoip")
            out.append("GeoIPv6File \(geoip)/geoip6")
        }
        out.append("")

        out.append("# --- Local listeners ----------------------------------------------")
        // A unix socket rather than a port: unreachable by other processes,
        // which a loopback listener never is.
        out.append("SocksPort unix:\(session.socksSocket) IsolateSOCKSAuth")
        // And on loopback too, for the mode where the tunnel cannot be loaded
        // and the system's proxies are pointed here instead. HTTP CONNECT is
        // what most applications honour, and it always carries the hostname
        // through, so nothing is resolved on the local network.
        out.append("SocksPort 127.0.0.1:\(session.socksPort) IsolateSOCKSAuth")
        out.append("HTTPTunnelPort 127.0.0.1:\(session.httpPort)")
        out.append("ControlSocket \(session.controlSocket)")
        out.append("CookieAuthentication 1")
        out.append("CookieAuthFile \(session.cookieFile)")
        out.append("")

        out.append("# --- Client role ---------------------------------------------------")
        out.append("ClientOnly 1")
        out.append("DormantCanceledByStartup 1")
        out.append("DormantTimeoutEnabled 0")
        out.append("")

        out.append("# --- Names -----------------------------------------------------------")
        // Only when asked for. The datapath resolves over TCP through
        // the proxy, so a DNSPort is usually one more listener for
        // nothing to read.
        if session.dnsPort > 0 {
            out.append("DNSPort 127.0.0.1:\(session.dnsPort)")
        }
        out.append("AutomapHostsOnResolve 1")
        out.append("AutomapHostsSuffixes .")
        out.append("VirtualAddrNetworkIPv4 \(virtualNetworkV4)")
        out.append("VirtualAddrNetworkIPv6 \(virtualNetworkV6)")
        out.append("")

        out.append("# --- Traffic shape ---------------------------------------------------")
        out.append("ConnectionPadding 1")
        out.append("ReducedConnectionPadding 0")
        out.append("")

        out.append("# --- Route -----------------------------------------------------------")
        // The first route is written in rather than applied afterwards: tor is
        // at its most reliable doing what it was started to do, with no
        // transition to react to. Only a change of mind needs the control port.
        if let opening = session.opening, opening.transport != .direct, !opening.bridges.isEmpty {
            out.append("UseBridges 1")
            for bridge in opening.bridges { out.append("Bridge \(bridge.raw)") }
        } else {
            out.append("UseBridges 0")
        }
        out.append("")

        out.append("# --- Circuits ---------------------------------------------------------")
        for (key, value) in tuning(for: session.opening?.transport ?? .direct) {
            out.append("\(key) \(value)")
        }
        out.append("")

        out.append("# --- Transports --------------------------------------------------------")
        // Declared for every transport that has a listener. tor does not
        // contact one until a bridge line names it, so listing them all costs
        // nothing and is what lets a route change avoid a restart.
        for (name, port) in session.plugins.sorted(by: { $0.key < $1.key }) {
            out.append("ClientTransportPlugin \(name) socks5 127.0.0.1:\(port)")
        }
        if session.plugins.isEmpty {
            out.append("# no transports available; only a direct connection can be tried")
        }
        return out.joined(separator: "\n") + "\n"
    }

    /// Circuit timings that suit the route actually in use.
    ///
    /// Tor's defaults are calibrated for a direct connection: ten seconds to
    /// build a circuit, a timeout then *learned* from observation, and ten
    /// minutes before a circuit stops taking new streams. Apply that to a path
    /// through a volunteer's browser and three things go wrong at once.
    /// Building takes longer than the timeout, so tor abandons circuits it was
    /// about to finish. The learned timeout trains on those failures and
    /// tightens rather than relaxing. And every ten minutes the next
    /// connection waits for a new circuit over that same slow path, which is
    /// exactly the periodic stall a Snowflake user notices without knowing
    /// where it comes from.
    static func tuning(for transport: Transport) -> [(String, String)] {
        switch transport {
        case .snowflake, .meek, .conjure:
            return [
                ("CircuitBuildTimeout", "90"),
                ("LearnCircuitBuildTimeout", "0"),
                ("CircuitStreamTimeout", "60"),
                ("MaxCircuitDirtiness", "1800"),
            ]
        case .webtunnel:
            return [
                ("CircuitBuildTimeout", "45"),
                ("LearnCircuitBuildTimeout", "0"),
                ("CircuitStreamTimeout", "30"),
                ("MaxCircuitDirtiness", "1200"),
            ]
        case .direct, .obfs4:
            return [
                ("CircuitBuildTimeout", "30"),
                ("LearnCircuitBuildTimeout", "1"),
                ("CircuitStreamTimeout", "0"),
                ("MaxCircuitDirtiness", "900"),
            ]
        }
    }
}
