#!/usr/bin/env node
// Writes internal/web/ui/css/rosa-stars.css: two tiles of stars (small SVG pictures, as data: URIs) for the night sky of the
// "Роса" look. The tiles are not the same size, so that laid side by side their pattern does not repeat in any way the eye can
// find; one of them twinkles against the other (css/rosa.css).
//
//   node web-dev/make-stars.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const out = path.join(path.dirname(fileURLToPath(import.meta.url)), "../internal/web/ui/css/rosa-stars.css");

/** A small seeded generator: the same stars every time. */
function rng(seed) {
  let s = seed >>> 0;
  return () => ((s = (s * 1664525 + 1013904223) >>> 0) / 4294967296);
}

function tile(seed, w, h, count, glints) {
  const r = rng(seed);
  const parts = [];
  const tones = ["#ffffff", "#ffffff", "#ffffff", "#fff1d6", "#d8e6ff"];
  for (let i = 0; i < count; i++) {
    const x = (r() * w).toFixed(1), y = (r() * h).toFixed(1);
    const big = r();
    const rad = big > 0.93 ? 1.5 : big > 0.7 ? 1.05 : big > 0.35 ? 0.75 : 0.55;
    const op = (0.4 + r() * 0.55).toFixed(2);
    parts.push(`<circle cx='${x}' cy='${y}' r='${rad}' fill='${tones[Math.floor(r() * tones.length)]}' fill-opacity='${op}'/>`);
  }
  for (let i = 0; i < glints; i++) {
    // a four-point glint
    const x = r() * (w - 20) + 10, y = r() * (h - 20) + 10, s = 4.5 + r() * 3;
    const f = (v) => v.toFixed(1);
    parts.push(`<path d='M${f(x)} ${f(y - s)}Q${f(x)} ${f(y)} ${f(x + s)} ${f(y)}Q${f(x)} ${f(y)} ${f(x)} ${f(y + s)}Q${f(x)} ${f(y)} ${f(x - s)} ${f(y)}Q${f(x)} ${f(y)} ${f(x)} ${f(y - s)}Z' fill='#fff' fill-opacity='.9'/>`);
  }
  return `<svg xmlns='http://www.w3.org/2000/svg' width='${w}' height='${h}' viewBox='0 0 ${w} ${h}'>${parts.join("")}</svg>`;
}

const enc = (s) => s.replace(/%/g, "%25").replace(/</g, "%3C").replace(/>/g, "%3E").replace(/#/g, "%23");
const a = tile(7, 331, 577, 46, 3);
const b = tile(19, 389, 701, 34, 2);
fs.writeFileSync(out, `/* Generated by web-dev/make-stars.mjs — do not edit by hand. Two tiles of stars for the night sky of the "Роса" look. */
html[data-look="rosa"] {
  --sky-stars-a: url("data:image/svg+xml,${enc(a)}");
  --sky-stars-b: url("data:image/svg+xml,${enc(b)}");
}
`);
console.log("wrote", out, fs.statSync(out).size, "bytes");
