// "Add device" modal: create an invite (whose device, regular/admin,
// validity), show the QR + code with a countdown, and flip to success when the
// invite is consumed and a new peer shows up. The inviter decides the owner:
// the joining device cannot claim one.
import { html, useEffect, useRef, useState } from "../../vendor/preact-htm.js";
import { Icon } from "../icons.js";
import { t } from "../i18n.js";
import { del, post } from "../api.js";
import { go, href } from "../router.js";
import { nowSec, state, useStore } from "../store.js";
import { fmtCountdown } from "../format.js";
import { useNow } from "../hooks.js";
import { DeviceAvatar } from "../components/avatar.js";
import { Button, Callout, CopyButton, Field, Segmented, Spinner } from "../components/ui.js";
import { Modal } from "../components/modal.js";
import { TechDetails } from "../components/misc.js";
import { toastError } from "../components/toast.js";
import { cx } from "../util.js";

/**
 * The QR SVG is generated by our own node. It is still not injected as HTML:
 * it is shown through an <img> data: URL, where SVG cannot run scripts.
 */
function QrImage({ svg, label, big = false }) {
  const src = svg ? "data:image/svg+xml;charset=utf-8," + encodeURIComponent(svg) : "";
  return html`<div class=${cx("qr", big && "qr--big")} data-testid=${big ? "invite-qr-big" : "invite-qr"}>${src ? html`<img src=${src} alt=${label} width="300" height="300" />` : html`<${Spinner} />`}</div>`;
}

/** Whose device the invitation was for: the invite says so; the joined peer carries the same owner. */
function inviteOwner(inv, joined) {
  return (inv && inv.owner) || (joined && joined.owner) || "";
}

const TTL = [
  { value: 15, label: "inv.ttl15" },
  { value: 60, label: "inv.ttl60" },
  { value: 1440, label: "inv.ttl1440" },
];

export function AddDeviceModal({ onClose }) {
  const self = useStore((s) => s.self);
  const invites = useStore((s) => s.invites);
  const peers = useStore((s) => s.peers);
  const [admin, setAdmin] = useState(false);
  const [owner, setOwner] = useState(() => (state.self && state.self.owner) || "");
  const [ttl, setTtl] = useState(60);
  const [busy, setBusy] = useState(false);
  const [inv, setInv] = useState(null);
  const [phase, setPhase] = useState("setup"); // setup | waiting | done | expired | gone
  const [big, setBig] = useState(false); // the QR shown large, for a camera that is not close
  const [joined, setJoined] = useState(null);
  const known = useRef(new Set(state.peers.map((p) => p.id)));
  useNow(1000);

  const goneAt = useRef(0);

  // Watch for the invite being consumed / expiring. The `invites` and `peers`
  // events may arrive in either order, so a vanished invite gets a short grace
  // period for the new peer to show up before we call it "gone".
  useEffect(() => {
    if (!inv || phase !== "waiting") return undefined;
    const still = invites.some((x) => x.id === inv.id);
    const fresh = peers.find((p) => !known.current.has(p.id));
    if (!still && fresh) {
      setJoined(fresh);
      setPhase("done");
      return undefined;
    }
    if (still) { goneAt.current = 0; return undefined; }
    if (nowSec() >= inv.expires) { setPhase("expired"); return undefined; }
    if (!goneAt.current) goneAt.current = Date.now();
    const tm = setTimeout(() => setPhase((ph) => (ph === "waiting" ? "gone" : ph)), 6000 - (Date.now() - goneAt.current));
    return () => clearTimeout(tm);
  }, [invites, peers, inv, phase]);

  useEffect(() => {
    if (phase === "waiting" && inv && nowSec() >= inv.expires && !state.peers.some((p) => !known.current.has(p.id))) setPhase("expired");
  });

  const create = async () => {
    setBusy(true);
    try {
      known.current = new Set(state.peers.map((p) => p.id));
      const r = await post("invites", { admin, ttlMinutes: ttl, owner: owner.trim().replace(/\s+/g, " ") });
      setInv(r);
      setPhase("waiting");
    } catch (e) {
      toastError(e);
    } finally {
      setBusy(false);
    }
  };

  const cancelInvite = async () => {
    if (inv) {
      try { await del(`invites/${encodeURIComponent(inv.id)}`); } catch (e) { if (e.code !== "notfound") toastError(e); }
    }
    onClose();
  };

  if (self && !self.admin) {
    const admins = state.peers.filter((p) => p.admin);
    return html`<${Modal} title=${t("add.title")} icon="userPlus" onClose=${onClose} size="sm"
        footer=${html`<${Button} variant="primary" onClick=${onClose}>${t("common.ok")}</${Button}>`}>
      <p class="muted">${t("add.notAdmin")}</p>
      ${admins.length > 0 && html`<ul class="stack stack--sm mt-3">
        ${admins.map((p) => html`<li class="row" key=${p.id}><${DeviceAvatar} dev=${p} size=${32} /><span class="strong">${p.name}</span><span class="faint small">${p.owner}</span></li>`)}
      </ul>`}
    </${Modal}>`;
  }

  if (phase === "setup") {
    return html`<${Modal} title=${t("add.title")} subtitle=${t("add.subtitle")} icon="userPlus" onClose=${onClose}
        footer=${html`
          <${Button} variant="ghost" onClick=${onClose}>${t("common.cancel")}</${Button}>
          <${Button} variant="primary" icon="qr" loading=${busy} onClick=${create} data-testid="invite-create">${t("add.create")}</${Button}>`}>
      <div class="stack stack--lg">
        <${Field} label=${t("add.owner")} hint=${t("add.ownerHint")}>
          ${(id, d) => html`<input id=${id} class="input" value=${owner} maxlength="64" autocomplete="off" data-testid="invite-owner"
            placeholder=${t("add.ownerPh")} aria-describedby=${d} onInput=${(e) => setOwner(e.target.value)} />`}
        </${Field}>
        <fieldset class="fieldset">
          <legend class="field__label">${t("add.role")}</legend>
          <div class="radio-cards">
            <label class=${cx("radio-card", !admin && "is-on")}>
              <input type="radio" name="role" checked=${!admin} onChange=${() => setAdmin(false)} />
              <span><span class="radio-card__title">${t("add.regular")}</span><span class="radio-card__text">${t("add.regularText")}</span></span>
            </label>
            <label class=${cx("radio-card", admin && "is-on")}>
              <input type="radio" name="role" checked=${admin} onChange=${() => setAdmin(true)} />
              <span><span class="radio-card__title">${t("add.admin")}</span><span class="radio-card__text">${t("add.adminText")}</span></span>
            </label>
          </div>
          ${admin && html`<${Callout} tone="warn" class="mt-2" title=${t("add.adminWarnTitle")}>${t("add.adminWarn")}</${Callout}>`}
        </fieldset>
        <div class="field">
          <span class="field__label" id="ttl-lbl">${t("add.validity")}</span>
          <${Segmented} label=${t("add.validity")} value=${ttl} full onChange=${setTtl}
            options=${TTL.map((o) => ({ value: o.value, label: t(o.label) }))} />
          <p class="field__hint">${t("add.validityHint")}</p>
        </div>
      </div>
    </${Modal}>`;
  }

  if (phase === "done") {
    return html`<${Modal} title=${t("add.doneTitle")} icon="checkCircle" onClose=${onClose} size="sm"
        footer=${html`
          <${Button} variant="ghost" onClick=${onClose}>${t("common.done")}</${Button}>
          ${joined && html`<${Button} variant="primary" icon="chevronRight" onClick=${() => { onClose(); go(href(["devices", joined.id])); }}>${t("add.openDevice")}</${Button}>`}`}>
      <div class="add-done" data-testid="invite-done">
        ${joined && html`<${DeviceAvatar} dev=${joined} size=${64} />`}
        <p class="add-done__title">${joined ? t("add.joined", { name: joined.name }) : t("add.joinedGeneric")}</p>
        ${inviteOwner(inv, joined) && html`<p class="add-done__for" data-testid="invite-for"><${Icon} name="user" size=${14} />${t("inv.for", { owner: inviteOwner(inv, joined) })}</p>`}
        <p class="muted">${t("add.joinedText")}</p>
      </div>
    </${Modal}>`;
  }

  if (phase === "expired" || phase === "gone") {
    return html`<${Modal} title=${phase === "expired" ? t("add.expiredTitle") : t("add.goneTitle")} icon="clock" tone="warn" onClose=${onClose} size="sm"
        footer=${html`
          <${Button} variant="ghost" onClick=${onClose}>${t("common.close")}</${Button}>
          <${Button} variant="primary" icon="refresh" onClick=${() => { setInv(null); setPhase("setup"); }}>${t("add.newInvite")}</${Button}>`}>
      <p class="muted">${phase === "expired" ? t("add.expiredText") : t("add.goneText")}</p>
    </${Modal}>`;
  }

  // waiting
  const left = inv ? inv.expires - nowSec() : 0;
  return html`<${Modal} title=${t("add.waitTitle")} icon="qr" onClose=${onClose} size="lg" testid="invite-modal"
      footer=${html`
        <${Button} variant="danger-ghost" icon="x" onClick=${cancelInvite}>${t("inv.cancel")}</${Button}>
        <span class="grow"></span>
        <${Button} variant="secondary" onClick=${onClose}>${t("add.hide")}</${Button}>`}>
    ${big && html`<${Modal} title=${t("add.qrBigTitle")} icon="qr" onClose=${() => setBig(false)} size="md" testid="invite-qr-modal">
      <div class="qr-big">
        <${QrImage} svg=${inv && inv.qrSvg} label=${t("add.qrAlt")} big />
        <p class="muted center">${t("add.qrBigText")}</p>
        <p class="invite__timer tnum" aria-live="off"><${Icon} name="clock" size=${14} /> ${t("add.validFor", { time: fmtCountdown(left) })}</p>
      </div>
    </${Modal}>`}
    <div class="invite">
      <div class="invite__qr">
        <${QrImage} svg=${inv && inv.qrSvg} label=${t("add.qrAlt")} />
        <${Button} variant="secondary" size="sm" icon="maximize" onClick=${() => setBig(true)} data-testid="invite-qr-enlarge">${t("add.qrBig")}</${Button}>
        <p class="invite__timer tnum" aria-live="off"><${Icon} name="clock" size=${14} /> ${t("add.validFor", { time: fmtCountdown(left) })}</p>
        <p class="faint xsmall center invite__tip">${t("add.qrTip")}</p>
      </div>
      <div class="invite__info stack">
        <ol class="steps">
          <li><span class="steps__n">1</span><span>${t("add.step1")}</span></li>
          <li><span class="steps__n">2</span><span>${t("add.step2")}</span></li>
          <li><span class="steps__n">3</span><span>${t("add.step3")}</span></li>
        </ol>
        <div class="field">
          <span class="field__label">${t("add.code")}</span>
          <div class="invite__code mono" data-testid="invite-code">${inv && inv.code}</div>
          <div class="row row--wrap"><${CopyButton} text=${inv ? inv.code : ""} variant="secondary" size="sm">${t("add.copyCode")}</${CopyButton}>
            ${inv && inv.owner && html`<span class="chip chip--outline" data-testid="invite-for"><${Icon} name="user" size=${14} />${t("inv.for", { owner: inv.owner })}</span>`}
            ${inv && inv.admin && html`<span class="chip chip--warn"><${Icon} name="shield" size=${14} />${t("inv.roleAdmin")}</span>`}</div>
        </div>
        ${inv && inv.endpoints && inv.endpoints.length > 0 && html`<${TechDetails} summary=${t("add.addrs")}>
          <p class="muted small">${t("add.addrsText")}</p>
          <ul class="mono xsmall invite__addrs" data-testid="invite-addrs">${inv.endpoints.map((e) => html`<li key=${e}>${e}</li>`)}</ul>
        </${TechDetails}>`}
        <div class="invite__wait" role="status" data-testid="invite-waiting">
          <span class="invite__pulse" aria-hidden="true"></span>
          <span>${t("add.waiting")}</span>
        </div>
      </div>
    </div>
  </${Modal}>`;
}
