#!/usr/bin/env python3
"""
Generates the animated weather layers for Papersky widgets.

Widgets are RemoteViews: the app cannot run code on the home screen. What the launcher *does*
run by itself is an indeterminate ProgressBar, and a ProgressBar happily loops an
AnimatedVectorDrawable on the render thread. Each effect below is such a drawable, paired with a
tiny RemoteViews layout that hosts it.

Every effect is drawn in a 100×100 viewport, white, and tinted at runtime from the scene
palette (ProgressBar#setIndeterminateTintList, SRC_IN), so one file serves every palette.
Two size classes keep strokes and speeds physically consistent: "s" is tuned for a square
side of ~180 dp, "l" for ~340 dp.

Run from the project root:  python3 tools/widget_fx.py
"""
import math
import os
import random

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DRAWABLE = os.path.join(ROOT, "app/src/main/res/drawable")
LAYOUT = os.path.join(ROOT, "app/src/main/res/layout")
HEADER = "<!-- Generated by tools/widget_fx.py — do not edit by hand. -->"

UNIT_DP = {"s": 1.8, "l": 3.4}  # dp per viewport unit for each size class

LINEAR = "@android:anim/linear_interpolator"
EASE = "@android:interpolator/accelerate_decelerate"


def f(v):
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


class Avd:
    def __init__(self):
        self.body = []
        self.targets = []

    def group(self, name, content, **attrs):
        a = "".join(f' android:{k}="{v}"' for k, v in attrs.items())
        n = f' android:name="{name}"' if name else ""
        self.body.append(f"        <group{n}{a}>\n{content}        </group>\n")

    def target(self, name, animators):
        inner = "".join(animators)
        if len(animators) > 1:
            inner = f"                <set>\n{inner}                </set>\n"
        self.targets.append(
            f'    <target android:name="{name}">\n'
            f'        <aapt:attr name="android:animation">\n{inner}        </aapt:attr>\n'
            f"    </target>\n"
        )

    def write(self, name):
        xml = (
            f'<?xml version="1.0" encoding="utf-8"?>\n{HEADER}\n'
            '<animated-vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    xmlns:aapt="http://schemas.android.com/aapt">\n'
            '    <aapt:attr name="android:drawable">\n'
            '        <vector android:width="100dp" android:height="100dp"\n'
            '            android:viewportWidth="100" android:viewportHeight="100">\n'
            + "".join(self.body)
            + "        </vector>\n    </aapt:attr>\n"
            + "".join(self.targets)
            + "</animated-vector>\n"
        )
        with open(os.path.join(DRAWABLE, name + ".xml"), "w") as fh:
            fh.write(xml)


def anim(prop, frm, to, ms, repeat="restart", interp=LINEAR, offset=0):
    o = f' android:startOffset="{offset}"' if offset else ""
    return (
        f'                <objectAnimator android:propertyName="{prop}" android:valueFrom="{f(frm)}" android:valueTo="{f(to)}"\n'
        f'                    android:duration="{int(ms)}" android:repeatCount="infinite" android:repeatMode="{repeat}"\n'
        f'                    android:valueType="floatType" android:interpolator="{interp}"{o} />\n'
    )


def keyframes(prop, ms, frames, offset=0):
    kf = "".join(f'                        <keyframe android:fraction="{f(fr)}" android:value="{f(v)}" />\n' for fr, v in frames)
    o = f' android:startOffset="{offset}"' if offset else ""
    return (
        f'                <objectAnimator android:duration="{int(ms)}" android:repeatCount="infinite"\n'
        f'                    android:interpolator="{LINEAR}"{o}>\n'
        f'                    <propertyValuesHolder android:propertyName="{prop}" android:valueType="floatType">\n'
        f"{kf}"
        f"                    </propertyValuesHolder>\n"
        f"                </objectAnimator>\n"
    )


def stroke_path(data, width, alpha, name=None):
    n = f' android:name="{name}"' if name else ""
    return (
        f'            <path{n} android:pathData="{data}" android:strokeColor="#FFFFFFFF"\n'
        f'                android:strokeWidth="{f(width)}" android:strokeAlpha="{f(alpha)}" android:strokeLineCap="round" />\n'
    )


def fill_path(data, alpha, name=None, gradient=None):
    n = f' android:name="{name}"' if name else ""
    if gradient:
        return (
            f'            <path{n} android:pathData="{data}" android:fillAlpha="{f(alpha)}">\n'
            f'                <aapt:attr name="android:fillColor">\n{gradient}                </aapt:attr>\n'
            f"            </path>\n"
        )
    return f'            <path{n} android:pathData="{data}" android:fillColor="#FFFFFFFF" android:fillAlpha="{f(alpha)}" />\n'


def radial(cx, cy, r, stops):
    items = "".join(f'                        <item android:offset="{f(o)}" android:color="{c}" />\n' for o, c in stops)
    return (
        f'                    <gradient android:type="radial" android:centerX="{f(cx)}" android:centerY="{f(cy)}" android:gradientRadius="{f(r)}">\n'
        f"{items}                    </gradient>\n"
    )


# ---- Precipitation --------------------------------------------------------------------------

RAIN_LAYERS = [  # len dp, width dp, alpha, speed dp/s, share — hairlines (DESIGN_DOCTRINE §10)
    (9, 0.6, 0.3, 430, 0.45),
    (15, 0.85, 0.42, 660, 0.33),
    (24, 1.1, 0.55, 950, 0.22),
]


def rain_layers(avd, rng, cls, density, slant, prefix="r"):
    u = UNIT_DP[cls]
    t = math.tan(math.radians(slant))
    area_dp = (100 * u) ** 2
    total = area_dp / 900 * density
    for li, (length, width, alpha, speed, share) in enumerate(RAIN_LAYERS):
        n = max(4, int(total * share))
        ln = length / u
        segs = []
        for _ in range(n):
            x = rng.uniform(-100 * t - 6, 106 + 100 * t)
            y = rng.uniform(0, 100)
            for dx, dy in ((0, 0), (-100 * t, -100)):
                segs.append(f"M{f(x + dx)},{f(y + dy)}l{f(ln * t)},{f(ln)}")
        name = f"{prefix}{li}"
        avd.group(name, stroke_path("".join(segs), width / u, alpha))
        ms = 100 * u / speed * 1000
        animators = [anim("translateY", 0, 100, ms)]
        if t > 0:
            animators.append(anim("translateX", 0, 100 * t, ms))
        avd.target(name, animators)


SNOW_LAYERS = [  # diameter dp, alpha, speed dp/s, share
    (1.2, 0.55, 18, 0.45),
    (2.0, 0.75, 30, 0.33),
    (3.0, 0.85, 48, 0.22),
]


def snow_layers(avd, rng, cls, density, prefix="s"):
    u = UNIT_DP[cls]
    area_dp = (100 * u) ** 2
    total = area_dp / 1300 * density
    for li, (diam, alpha, speed, share) in enumerate(SNOW_LAYERS):
        n = max(5, int(total * share))
        fall = f"{prefix}{li}"
        subgroups = []
        for sg in range(3):
            dots = []
            for _ in range(max(2, n // 3)):
                x = rng.uniform(-8, 108)
                y = rng.uniform(0, 100)
                for dy in (0, -100):
                    dots.append(f"M{f(x)},{f(y + dy)}l0,0.01")
            data = "".join(dots)
            content = ""
            if li == 2:  # near flakes get a soft halo
                content += stroke_path(data, diam * 2.3 / u, 0.2)
            content += stroke_path(data, diam / u, alpha)
            sway = f"{fall}w{sg}"
            subgroups.append((sway, content))
        inner = "".join(f'            <group android:name="{n_}">\n{c}            </group>\n' for n_, c in subgroups)
        avd.group(fall, inner)
        ms = 100 * u / speed * 1000
        avd.target(fall, [anim("translateY", 0, 100, ms)])
        for sg, (sway, _) in enumerate(subgroups):
            amp = (5 + 4 * sg) / u
            avd.target(sway, [anim("translateX", -amp, amp, 2600 + 900 * sg + 400 * li, repeat="reverse", interp=EASE, offset=300 * sg)])


def hail_layers(avd, rng, cls, prefix="h"):
    u = UNIT_DP[cls]
    for li, (diam, alpha, speed, n) in enumerate([(2.0, 0.8, 560, 18), (2.8, 0.95, 800, 12)]):
        dots = []
        for _ in range(n if cls == "l" else n // 2 + 3):
            x = rng.uniform(-4, 104)
            y = rng.uniform(0, 100)
            for dy in (0, -100):
                dots.append(f"M{f(x)},{f(y + dy)}l0,0.01")
        name = f"{prefix}{li}"
        avd.group(name, stroke_path("".join(dots), diam / u, alpha))
        avd.target(name, [anim("translateY", 0, 100, 100 * u / speed * 1000)])


def drizzle_layers(avd, rng, cls, prefix="d"):
    u = UNIT_DP[cls]
    area_dp = (100 * u) ** 2
    for li, (length, width, alpha, speed, k) in enumerate([(4, 0.7, 0.3, 200, 0.55), (6, 0.9, 0.45, 290, 0.45)]):
        n = max(8, int(area_dp / 650 * k))
        segs = []
        for _ in range(n):
            x = rng.uniform(-4, 104)
            y = rng.uniform(0, 100)
            for dy in (0, -100):
                segs.append(f"M{f(x)},{f(y + dy)}l0,{f(length / u)}")
        name = f"{prefix}{li}"
        avd.group(name, stroke_path("".join(segs), width / u, alpha))
        avd.target(name, [anim("translateY", 0, 100, 100 * u / speed * 1000)])


# ---- Sky ------------------------------------------------------------------------------------

def sparkle(x, y, r):
    k = r * 0.22
    return (f"M{f(x)},{f(y - r)}Q{f(x + k)},{f(y - k)} {f(x + r)},{f(y)}Q{f(x + k)},{f(y + k)} {f(x)},{f(y + r)}"
            f"Q{f(x - k)},{f(y + k)} {f(x - r)},{f(y)}Q{f(x - k)},{f(y - k)} {f(x)},{f(y - r)}Z")


def stars(avd, rng, cls):
    u = UNIT_DP[cls]
    count = 44 if cls == "l" else 26
    for g in range(4):
        dots = []
        for _ in range(count // 4):
            v = rng.random()
            dots.append(f"M{f(rng.uniform(2, 98))},{f(2 + v * v * 74)}l0,0.01")
        name = f"tw{g}"
        avd.body.append(stroke_path("".join(dots), (0.9 + 0.3 * g) / u, 0.9, name=name))
        avd.target(name, [anim("strokeAlpha", 0.18, 0.95, 1500 + 520 * g, repeat="reverse", interp=EASE, offset=380 * g)])
    for b in range(3 if cls == "l" else 2):
        name = f"sp{b}"
        r = (3.2 + rng.random() * 1.8) / u
        avd.body.append(fill_path(sparkle(rng.uniform(8, 92), rng.uniform(4, 50), r), 0.9, name=name))
        avd.target(name, [anim("fillAlpha", 0.1, 1, 1900 + 700 * b, repeat="reverse", interp=EASE, offset=500 * b)])


def motes(avd, rng, cls):
    u = UNIT_DP[cls]
    for g in range(2):
        dots = []
        for _ in range(8 if cls == "l" else 5):
            x = rng.uniform(4, 96)
            y = rng.uniform(0, 100)
            for dy in (0, 100):
                dots.append(f"M{f(x)},{f(y + dy)}l0,0.01")
        data = "".join(dots)
        core = f"mc{g}"
        name = f"m{g}"
        avd.group(name, stroke_path(data, 7 / u, 0.1) + stroke_path(data, 3 / u, 0.5, name=core))
        # Dust rises slowly through the light and glints as it turns.
        avd.target(name, [anim("translateY", 0, -100, 100 * u / (5 + 3 * g) * 1000)])
        avd.target(core, [anim("strokeAlpha", 0.12, 0.6, 2300 + 900 * g, repeat="reverse", interp=EASE, offset=600 * g)])


def fog(avd):
    grad = radial(0, 0, 50, [(0, "#99FFFFFF"), (0.55, "#40FFFFFF"), (1, "#00FFFFFF")])
    circle = "M-50,0a50,50 0 1,0 100,0a50,50 0 1,0 -100,0"
    for i, (x, y, sx, sy, ms) in enumerate([(30, 58, 1.1, 0.26, 21000), (72, 74, 1.3, 0.22, 26000), (40, 90, 1.5, 0.3, 31000)]):
        name = f"fog{i}"
        inner = (f'            <group android:scaleX="{f(sx)}" android:scaleY="{f(sy)}">\n'
                 + fill_path(circle, 1, gradient=grad)
                 + "            </group>\n")
        avd.group(name, inner, translateX=f(x), translateY=f(y))
        avd.target(name, [anim("translateX", x - 16, x + 16, ms, repeat="reverse", interp=EASE)])


def flash(avd):
    frames = [(0, 0), (0.62, 0), (0.625, 0.75), (0.64, 0.15), (0.652, 0.6), (0.7, 0), (0.86, 0), (0.864, 0.35), (0.9, 0), (1, 0)]
    avd.body.append(fill_path("M0,0h100v100h-100z", 0, name="sheet"))
    avd.target("sheet", [keyframes("fillAlpha", 7300, frames)])
    bolt = "M47,6L43,24L51,27L44,46L53,49L47,70M44,46L36,58M51,27L60,35"
    bframes = [(0, 0), (0.62, 0), (0.625, 1), (0.64, 0.3), (0.652, 1), (0.7, 0), (1, 0)]
    avd.body.append(
        f'            <path android:name="bolt" android:pathData="{bolt}" android:strokeColor="#FFFFFFFF"\n'
        f'                android:strokeWidth="1.1" android:strokeAlpha="0" android:strokeLineCap="round" android:strokeLineJoin="round" />\n'
    )
    avd.target("bolt", [keyframes("strokeAlpha", 7300, bframes)])


def rays(avd):
    """The sun's halo breathing: a soft glow and two hairline rings of tracing paper."""
    glow = radial(50, 50, 34, [(0, "#88FFFFFF"), (0.5, "#33FFFFFF"), (1, "#00FFFFFF")])
    avd.body.append(fill_path("M16,50a34,34 0 1,0 68,0a34,34 0 1,0 -68,0", 0.8, name="glow", gradient=glow))
    avd.target("glow", [anim("fillAlpha", 0.4, 0.9, 4200, repeat="reverse", interp=EASE)])
    rings = stroke_path("M50,26a24,24 0 1,0 0.01,0ZM50,14a36,36 0 1,0 0.01,0Z", 0.5, 0.5, name="rings")
    avd.group("breath", rings, pivotX="50", pivotY="50")
    avd.target("breath", [anim("scaleX", 0.94, 1.06, 4200, repeat="reverse", interp=EASE), anim("scaleY", 0.94, 1.06, 4200, repeat="reverse", interp=EASE)])
    avd.target("rings", [anim("strokeAlpha", 0.2, 0.55, 4200, repeat="reverse", interp=EASE)])


def hearth(avd):
    """Firelight: a warm glow flickering at two unrelated rates, and sparks rising from the logs."""
    glow = radial(50, 58, 42, [(0, "#AAFFFFFF"), (0.45, "#44FFFFFF"), (1, "#00FFFFFF")])
    avd.body.append(fill_path("M8,58a42,42 0 1,0 84,0a42,42 0 1,0 -84,0", 0.7, name="glow", gradient=glow))
    avd.target("glow", [keyframes("fillAlpha", 1900, [(0, 0.55), (0.13, 0.8), (0.21, 0.5), (0.37, 0.9), (0.5, 0.62),
                                                      (0.63, 0.85), (0.78, 0.5), (0.9, 0.75), (1, 0.55)])])
    core = radial(50, 66, 20, [(0, "#CCFFFFFF"), (1, "#00FFFFFF")])
    avd.body.append(fill_path("M30,66a20,20 0 1,0 40,0a20,20 0 1,0 -40,0", 0.6, name="core", gradient=core))
    avd.target("core", [keyframes("fillAlpha", 1300, [(0, 0.5), (0.2, 0.85), (0.35, 0.45), (0.6, 0.8), (0.8, 0.55), (1, 0.5)])])
    rng = random.Random("hearth")
    for i in range(7):
        x = rng.uniform(38, 62)
        name, dot = f"sp{i}", f"spd{i}"
        ms = rng.uniform(1500, 2600)
        off = int(rng.uniform(0, 2400))
        avd.group(name, stroke_path(f"M{f(x)},66l0,0.01", 1.4, 0, name=dot))
        drift = rng.uniform(-6, 6)
        avd.target(name, [anim("translateY", 0, -44, ms, offset=off, interp=EASE), anim("translateX", 0, drift, ms, offset=off)])
        avd.target(dot, [keyframes("strokeAlpha", ms, [(0, 0), (0.08, 0.95), (0.6, 0.5), (1, 0)], offset=off)])


# ---- Layouts --------------------------------------------------------------------------------

def layout(name):
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
{HEADER}
<!-- Hosts one animated weather layer. The bar is laid out at half size and scaled 2× so the
     vector is rasterised at a quarter of the pixels — rain and snow look softer, not worse. -->
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:importantForAccessibility="noHideDescendants">

    <ProgressBar
        android:id="@+id/fx"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_gravity="top|start"
        android:clickable="false"
        android:focusable="false"
        android:importantForAccessibility="no"
        android:indeterminate="true"
        android:indeterminateDrawable="@drawable/{name}"
        android:indeterminateOnly="false"
        android:maxHeight="4000dp"
        android:maxWidth="4000dp"
        android:minHeight="0dp"
        android:minWidth="0dp"
        android:mirrorForRtl="true"
        android:scaleX="2"
        android:scaleY="2" />
</FrameLayout>
'''
    with open(os.path.join(LAYOUT, "rv_" + name + ".xml"), "w") as fh:
        fh.write(xml)


def main():
    for d in (DRAWABLE, LAYOUT):
        for fn in os.listdir(d):
            if fn.startswith("wfx_") or fn.startswith("rv_wfx_"):
                os.remove(os.path.join(d, fn))
    names = []

    def emit(name, build):
        avd = Avd()
        build(avd, random.Random(name))
        avd.write(name)
        layout(name)
        names.append(name)

    for cls in ("s", "l"):
        for level, density in ((1, 0.45), (2, 1.0), (3, 1.7)):
            for wind, slant in (("calm", 7), ("windy", 24)):
                emit(f"wfx_rain{level}_{wind}_{cls}", lambda a, r, c=cls, d=density, s=slant: rain_layers(a, r, c, d, s))
            emit(f"wfx_snow{level}_{cls}", lambda a, r, c=cls, d=density: snow_layers(a, r, c, d))
        emit(f"wfx_drizzle_{cls}", lambda a, r, c=cls: drizzle_layers(a, r, c))
        emit(f"wfx_hail_{cls}", lambda a, r, c=cls: hail_layers(a, r, c))
        emit(f"wfx_sleet_{cls}", lambda a, r, c=cls: (rain_layers(a, r, c, 0.45, 10), snow_layers(a, r, c, 0.5, prefix="z")))
        emit(f"wfx_stars_{cls}", lambda a, r, c=cls: stars(a, r, c))
        emit(f"wfx_motes_{cls}", lambda a, r, c=cls: motes(a, r, c))
    emit("wfx_fog", lambda a, r: fog(a))
    emit("wfx_flash", lambda a, r: flash(a))
    emit("wfx_rays", lambda a, r: rays(a))
    emit("wfx_hearth", lambda a, r: hearth(a))
    print(f"{len(names)} effects written")


if __name__ == "__main__":
    main()
