// Package tor generates torrc files, runs tor.exe and talks to its control port.
package tor

import (
	"fmt"
	"strings"

	"torss/internal/config"
)

// Layout describes where the Tor Expert Bundle lives. tor is started with
// Dir as working directory so that the pluggable transport paths can stay
// relative (Tor cannot cope with spaces in ClientTransportPlugin exec paths).
type Layout struct {
	Dir        string // .../bin/tor (contains tor.exe, pluggable_transports/, data/)
	Exe        string // tor binary name relative to Dir, e.g. "tor.exe"
	Lyrebird   string // relative path, e.g. "pluggable_transports\lyrebird.exe"
	Conjure    string // relative path or "" if absent
	GeoIP      string // relative path or ""
	GeoIP6     string // relative path or ""
	HasConjure bool
}

// Options for Torrc.
type Options struct {
	DataDir  string // absolute path for DataDirectory
	Ports    config.Ports
	Mode     config.Mode
	Bridges  []string // bridge lines for bridge modes
	LogLevel string   // "notice" or "info"/"debug"
}

// Torrc renders the torrc for the given mode.
func Torrc(l Layout, o Options) (string, error) {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	level := "notice"
	if o.LogLevel == "debug" {
		level = "info"
	}
	w("# generated by torss - do not edit, it is rewritten on every connect")
	w("DataDirectory %s", o.DataDir)
	w("SocksPort 127.0.0.1:%d", o.Ports.TorSocks)
	w("DNSPort 127.0.0.1:%d", o.Ports.TorDNS)
	w("ControlPort 127.0.0.1:%d", o.Ports.TorControl)
	w("CookieAuthentication 1")
	w("ClientOnly 1")
	w("AvoidDiskWrites 1")
	w("DormantCanceledByStartup 1")
	w("Log %s stdout", level)
	if l.GeoIP != "" {
		w("GeoIPFile %s", l.GeoIP)
	}
	if l.GeoIP6 != "" {
		w("GeoIPv6File %s", l.GeoIP6)
	}
	w("ClientTransportPlugin meek_lite,obfs2,obfs3,obfs4,scramblesuit,webtunnel exec %s", l.Lyrebird)
	w("ClientTransportPlugin snowflake exec %s", l.Lyrebird)
	if l.HasConjure && l.Conjure != "" {
		w("ClientTransportPlugin conjure exec %s -registerURL https://registration.refraction.network/api", l.Conjure)
	}

	switch o.Mode {
	case config.ModeSSTor:
		// Every OR / directory connection goes through the local SOCKS that
		// sing-box forwards to the Shadowsocks server. The censor sees only
		// (Shadow)TLS to your VPS; Tor guards are reached from abroad.
		w("Socks5Proxy 127.0.0.1:%d", o.Ports.SSEntry)
	case config.ModeTorDirect:
		// nothing extra
	default:
		if o.Mode.Transport() == "" {
			return "", fmt.Errorf("mode %s does not use tor", o.Mode)
		}
		if len(o.Bridges) == 0 {
			return "", fmt.Errorf("no %s bridges available", o.Mode.Transport())
		}
		w("UseBridges 1")
		for _, line := range o.Bridges {
			w("Bridge %s", line)
		}
	}
	return b.String(), nil
}
