package tor

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Ports groups the loopback ports Tor listens on. Zero means "pick a free
// port at startup".
type Ports struct {
	SOCKS   int
	Control int
	DNS     int
}

// TorrcOptions describes everything needed to render a torrc.
type TorrcOptions struct {
	DataDir   string
	Binaries  Binaries
	Ports     Ports
	Transport Transport
	Bridges   []string

	// Extra holds additional "key value" options, used mainly by the traffic
	// shaping profiles to drive Tor's own padding machinery.
	Extra map[string]string

	// OwningPID makes Tor exit when the controller process goes away, so a
	// crashed UI can never leave an orphaned Tor running with an open SOCKS
	// port.
	OwningPID int
}

// RenderTorrc produces the torrc body.
func RenderTorrc(o TorrcOptions) (string, error) {
	if o.Ports.SOCKS == 0 || o.Ports.Control == 0 || o.Ports.DNS == 0 {
		return "", fmt.Errorf("torrc: ports must be assigned before rendering")
	}

	var b strings.Builder
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}

	w("# Generated by TorVeil. Edits are overwritten on every start.")
	w("DataDirectory %s", quotePath(o.DataDir))
	w("ClientOnly 1")
	w("AvoidDiskWrites 1")
	w("")

	w("# Loopback listeners. IsolateDestAddr/IsolateDestPort give each")
	w("# destination its own stream isolation so one site cannot be linked to")
	w("# another through a shared circuit.")
	w("SocksPort 127.0.0.1:%d IsolateDestAddr IsolateDestPort IsolateSOCKSAuth", o.Ports.SOCKS)
	w("SocksPolicy accept 127.0.0.1/32")
	w("SocksPolicy reject *")
	w("ControlPort 127.0.0.1:%d", o.Ports.Control)
	w("CookieAuthentication 1")
	w("DNSPort 127.0.0.1:%d", o.Ports.DNS)
	w("AutomapHostsOnResolve 1")
	w("AutomapHostsSuffixes .onion,.exit")
	if o.OwningPID > 0 {
		w("__OwningControllerProcess %d", o.OwningPID)
	}
	w("")

	if o.Binaries.GeoIP != "" {
		w("GeoIPFile %s", quotePath(o.Binaries.GeoIP))
	}
	if o.Binaries.GeoIPv6 != "" {
		w("GeoIPv6File %s", quotePath(o.Binaries.GeoIPv6))
	}
	w("")

	switch o.Transport {
	case TransportSnowflake:
		if o.Binaries.Snowflake == "" {
			return "", fmt.Errorf("torrc: snowflake selected but snowflake-client was not found")
		}
		w("# Snowflake: the first hop is a volunteer WebRTC proxy, and the")
		w("# broker is reached by domain fronting, so an observer sees a")
		w("# WebRTC session to a CDN rather than a connection to Tor.")
		w("UseBridges 1")
		w("ClientTransportPlugin snowflake exec %s", quotePath(o.Binaries.Snowflake))
		if err := writeBridges(w, o.Bridges, "snowflake"); err != nil {
			return "", err
		}
	case TransportObfs4:
		if o.Binaries.Obfs4 == "" {
			return "", fmt.Errorf("torrc: obfs4 selected but lyrebird/obfs4proxy was not found")
		}
		w("UseBridges 1")
		w("ClientTransportPlugin obfs4 exec %s", quotePath(o.Binaries.Obfs4))
		if err := writeBridges(w, o.Bridges, "obfs4"); err != nil {
			return "", err
		}
	case TransportDirect, "":
		w("# Direct connection to the Tor network (no pluggable transport).")
		w("UseBridges 0")
	default:
		return "", fmt.Errorf("torrc: unknown transport %q", o.Transport)
	}
	w("")

	if len(o.Extra) > 0 {
		w("# Options set by the active traffic-shaping profile.")
		keys := make([]string, 0, len(o.Extra))
		for k := range o.Extra {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			w("%s %s", k, o.Extra[k])
		}
	}

	return b.String(), nil
}

func writeBridges(w func(string, ...any), bridges []string, want string) error {
	n := 0
	for _, line := range bridges {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parsed, err := ParseBridgeLine(line)
		if err != nil {
			return fmt.Errorf("torrc: %w", err)
		}
		if parsed.Transport != want {
			continue
		}
		w("Bridge %s", line)
		n++
	}
	if n == 0 {
		return fmt.Errorf("torrc: no %s bridge lines configured", want)
	}
	return nil
}

// WriteTorrc renders the configuration and writes it into the data directory.
func WriteTorrc(o TorrcOptions) (string, error) {
	body, err := RenderTorrc(o)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(o.DataDir, 0o700); err != nil {
		return "", fmt.Errorf("create data directory: %w", err)
	}
	path := filepath.Join(o.DataDir, "torrc")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		return "", fmt.Errorf("write torrc: %w", err)
	}
	return path, nil
}

// quotePath renders a path as a torrc value. Tor accepts C-style quoted
// strings, which is what Windows paths need since they contain backslashes.
func quotePath(p string) string {
	if p == "" {
		return `""`
	}
	esc := strings.ReplaceAll(p, `\`, `\\`)
	esc = strings.ReplaceAll(esc, `"`, `\"`)
	return `"` + esc + `"`
}
