package app.veil.vpn.tor

import app.veil.vpn.model.BridgeLine
import app.veil.vpn.model.Transport

/**
 * Builds the torrc for one attempt.
 *
 * A few choices here are load-bearing and worth spelling out:
 *
 *  - `AutomapHostsOnResolve` with a suffix of `.` makes tor's DNSPort answer
 *    every name with a virtual address it remembers. When the tunnel later
 *    connects to that address, tor recovers the original hostname. Without it a
 *    transparent proxy resolves names at the exit and then connects by raw IP,
 *    which breaks any host served by a CDN and throws away per-name circuit
 *    isolation.
 *  - Bridge lines and the matching `ClientTransportPlugin` always travel
 *    together. A `UseBridges 1` without a usable plugin is a silent hang.
 *  - Padding is left on. Mobile Tor apps routinely turn it down to save
 *    battery, but the traffic-shape analysis that current DPI applies is
 *    exactly what padding is there to frustrate.
 *  - Nothing is written that would let tor keep an on-disk log.
 */
object Torrc {

    /** Virtual address space handed out by AutomapHostsOnResolve. */
    const val VIRTUAL_NETWORK_V4 = "10.192.0.0/10"
    const val VIRTUAL_NETWORK_V6 = "[FC00::]/7"

    data class Plan(
        val transport: Transport,
        val bridges: List<BridgeLine>,
        /** Local SOCKS port of the pluggable transport, when one is used. */
        val transportPort: Int?,
    )

    fun build(plan: Plan): String = buildString {
        appendLine("# Generated by Veil. Do not edit; it is rewritten on every connect.")
        appendLine()

        appendLine("# --- Local listeners --------------------------------------------")
        // A random port rather than 9050. Guides for identifying circumvention
        // software on a device list the usual proxy ports, and there is no
        // reason to answer on one of them.
        //
        // A unix socket in the app's private directory would close this off
        // entirely, since no other app could reach it. It is not used because
        // the tor service this app embeds parses `net/listeners/socks` as a
        // number and dies on a `unix:` value; the native tunnel already
        // supports connecting over a unix socket, so this becomes a one-line
        // change if that is ever fixed upstream.
        appendLine("SocksPort auto IsolateSOCKSAuth ExtendedErrors")
        appendLine("SocksPolicy accept 127.0.0.1/8")
        appendLine("SocksPolicy accept [::1]/128")
        appendLine("SocksPolicy reject *")
        // 8118 is Privoxy's port and nothing here needs an HTTP proxy: one
        // fewer listener is one fewer thing to find.
        appendLine("HTTPTunnelPort 0")
        appendLine()

        appendLine("# --- Client role -------------------------------------------------")
        appendLine("ClientOnly 1")
        appendLine("AvoidDiskWrites 1")
        appendLine("DormantCanceledByStartup 1")
        appendLine("DormantTimeoutEnabled 0")
        appendLine("DisableNetwork 0")
        appendLine()

        appendLine("# --- Names -------------------------------------------------------")
        appendLine("DNSPort auto")
        appendLine("AutomapHostsOnResolve 1")
        appendLine("AutomapHostsSuffixes .")
        appendLine("VirtualAddrNetworkIPv4 $VIRTUAL_NETWORK_V4")
        appendLine("VirtualAddrNetworkIPv6 $VIRTUAL_NETWORK_V6")
        appendLine("ClientDNSRejectInternalAddresses 1")
        appendLine()

        appendLine("# --- Traffic shape ------------------------------------------------")
        // Netflow padding hides connection start and end times from anything
        // watching volumes; circuit padding hides the shape of what is inside.
        // Both default to on for clients; they are stated here so that a later
        // battery optimisation cannot quietly remove them.
        appendLine("ConnectionPadding 1")
        appendLine("ReducedConnectionPadding 0")
        appendLine("CircuitPadding 1")
        appendLine("ReducedCircuitPadding 0")
        appendLine()

        appendLine("# --- Circuits ----------------------------------------------------")
        // A slow first hop is the usual reason a censored connection feels
        // broken; giving up sooner and trying another guard beats waiting.
        appendLine("CircuitBuildTimeout 30")
        appendLine("LearnCircuitBuildTimeout 1")
        appendLine("NewCircuitPeriod 120")
        appendLine("MaxCircuitDirtiness 600")
        // KeepalivePeriod is deliberately left at tor's default. A short, fixed
        // keepalive produces exactly the pattern traffic analysis looks for —
        // small packets at a regular interval, which is what distinguishes a
        // long-lived tunnel from a browser. The randomised connection padding
        // configured above already keeps the connection alive, without the
        // metronome.
        appendLine()

        appendLine("# --- Reaching the network ---------------------------------------")
        if (plan.transport == Transport.DIRECT) {
            appendLine("UseBridges 0")
        } else {
            require(plan.transportPort != null) {
                "transport ${plan.transport.torName} needs a local SOCKS port"
            }
            appendLine("UseBridges 1")
            appendLine("ClientTransportPlugin ${plan.transport.torName} socks5 127.0.0.1:${plan.transportPort}")
            if (plan.bridges.isEmpty()) {
                appendLine("# no bridge lines: tor will refuse to start, this is a bug")
            }
            plan.bridges.forEach { appendLine(it.torrcLine()) }
        }
    }
}
