package app.veil.vpn.tor

import app.veil.vpn.model.BridgeLine
import app.veil.vpn.model.Transport

/**
 * Builds the torrc for one attempt.
 *
 * A few choices here are load-bearing and worth spelling out:
 *
 *  - `AutomapHostsOnResolve` with a suffix of `.` makes tor's DNSPort answer
 *    every name with a virtual address it remembers. When the tunnel later
 *    connects to that address, tor recovers the original hostname. Without it a
 *    transparent proxy resolves names at the exit and then connects by raw IP,
 *    which breaks any host served by a CDN and throws away per-name circuit
 *    isolation.
 *  - Bridge lines and the matching `ClientTransportPlugin` always travel
 *    together. A `UseBridges 1` without a usable plugin is a silent hang.
 *  - Nothing is written that would let tor keep an on-disk log.
 */
object Torrc {

    /** Virtual address space handed out by AutomapHostsOnResolve. */
    const val VIRTUAL_NETWORK_V4 = "10.192.0.0/10"
    const val VIRTUAL_NETWORK_V6 = "[FC00::]/7"

    data class Plan(
        val transport: Transport,
        val bridges: List<BridgeLine>,
        /** Local SOCKS port of the pluggable transport, when one is used. */
        val transportPort: Int?,
    )

    fun build(plan: Plan): String = buildString {
        appendLine("# Generated by Veil. Do not edit; it is rewritten on every connect.")
        appendLine()

        appendLine("# --- Client role -------------------------------------------------")
        appendLine("ClientOnly 1")
        appendLine("SocksPolicy accept 127.0.0.1/8")
        appendLine("SocksPolicy reject *")
        appendLine("AvoidDiskWrites 1")
        appendLine("DormantCanceledByStartup 1")
        appendLine("DormantTimeoutEnabled 0")
        appendLine("DisableNetwork 0")
        appendLine()

        appendLine("# --- Names -------------------------------------------------------")
        appendLine("DNSPort auto")
        appendLine("AutomapHostsOnResolve 1")
        appendLine("AutomapHostsSuffixes .")
        appendLine("VirtualAddrNetworkIPv4 $VIRTUAL_NETWORK_V4")
        appendLine("VirtualAddrNetworkIPv6 $VIRTUAL_NETWORK_V6")
        appendLine("ClientDNSRejectInternalAddresses 1")
        appendLine()

        appendLine("# --- Circuits ----------------------------------------------------")
        // A slow first hop is the usual reason a censored connection feels
        // broken; giving up sooner and trying another guard beats waiting.
        appendLine("CircuitBuildTimeout 30")
        appendLine("LearnCircuitBuildTimeout 1")
        appendLine("NewCircuitPeriod 120")
        appendLine("MaxCircuitDirtiness 600")
        appendLine("KeepalivePeriod 60")
        appendLine()

        appendLine("# --- Reaching the network ---------------------------------------")
        if (plan.transport == Transport.DIRECT) {
            appendLine("UseBridges 0")
        } else {
            require(plan.transportPort != null) {
                "transport ${plan.transport.torName} needs a local SOCKS port"
            }
            appendLine("UseBridges 1")
            appendLine("ClientTransportPlugin ${plan.transport.torName} socks5 127.0.0.1:${plan.transportPort}")
            if (plan.bridges.isEmpty()) {
                appendLine("# no bridge lines: tor will refuse to start, this is a bug")
            }
            plan.bridges.forEach { appendLine(it.torrcLine()) }
        }
    }
}
