package app.veil.vpn.tor

import app.veil.vpn.model.Transport

/**
 * Builds the torrc for a whole session, not for one attempt.
 *
 * This used to write a fresh torrc per rung and restart tor each time, which
 * was the single worst decision in the app. Restarting tor costs half a minute
 * before the first byte moves, and worse, it does not reliably work: the tor
 * service serialises startup on a static lock, tor itself locks its data
 * directory, and the previous instance is often still shutting down when the
 * next one tries to start. From the second rung onwards, "nothing works" was
 * usually us, not the network.
 *
 * So tor is started once with every transport plugin declared, and rungs are
 * switched over the control port instead — a `SETCONF` away rather than a
 * restart away. Everything a bridge needs beyond its address travels in the
 * bridge line itself, which the transports read per connection.
 *
 * Other choices worth spelling out:
 *
 *  - The SOCKS and DNS ports are named explicitly rather than left on `auto`.
 *    See [Session] for why; it is not a style preference, it is the difference
 *    between the tunnel finding tor and not.
 *  - `AutomapHostsOnResolve` with a suffix of `.` makes tor's DNSPort answer
 *    every name with a virtual address it remembers, so the tunnel can recover
 *    the hostname when it connects. Without it a transparent proxy resolves at
 *    the exit and connects by raw IP, which breaks anything behind a CDN.
 *  - Padding stays on. Mobile Tor apps routinely turn it down for battery, but
 *    traffic-shape analysis is exactly what it is there to frustrate.
 *  - Nothing is written that would let tor keep a log on disk.
 */
object Torrc {

    /** Virtual address space handed out by AutomapHostsOnResolve. */
    const val VIRTUAL_NETWORK_V4 = "10.192.0.0/10"
    const val VIRTUAL_NETWORK_V6 = "[FC00::]/7"

    /**
     * @param plugins every transport that has a listener, and its local port.
     * @param socksPort the port tor must publish SOCKS on.
     * @param dnsPort the port tor must answer DNS on.
     * @param opening the first rung, written straight into the configuration.
     *
     * The first rung is in the file rather than applied afterwards over the
     * control port, and that is deliberate. Tor is at its most reliable doing
     * what it was started to do: it reads the bridges, opens its listeners and
     * begins, with no transition to react to and nothing that has to arrive in
     * the right order. Only the second rung onwards is a change of mind, and
     * only that needs the control port.
     *
     * The two ports are chosen by the app and written in, rather than left as
     * `SocksPort auto`, for a reason that took a while to find and is worth
     * recording. Tor opens its listeners inside `options_act`, and it is passed
     * `DisableNetwork` as its "close everything except the control port" flag.
     * So while the network is off there is no SOCKS listener and no DNS
     * listener at all, and `GETINFO net/listeners/socks` answers with an empty
     * string. Asking tor where it is listening before enabling the network
     * therefore returns nothing, which the app used to read as "tor failed to
     * start" — and every route failed before a single packet was sent.
     *
     * Worse, `auto` means port zero, so each time the network is switched off
     * and on again to change route, tor binds a *different* ephemeral port.
     * Measured against tor 0.4.8: 43335, then 39025 for the same session. Any
     * address read once at startup is wrong from the second rung onwards.
     *
     * Naming the ports fixes both. They are still random — picked from the
     * ephemeral range at connect time — because a fixed 9050 is what a guide to
     * spotting circumvention software on a phone tells you to look for.
     */
    data class Session(
        val plugins: Map<Transport, Int>,
        val socksPort: Int,
        val dnsPort: Int,
        val opening: Attempt? = null,
    )

    fun build(session: Session): String = buildString {
        appendLine("# Generated by Veil. Rewritten whenever the tunnel starts.")
        appendLine()

        appendLine("# --- Local listeners --------------------------------------------")
        appendLine("SocksPort 127.0.0.1:${session.socksPort} IsolateSOCKSAuth")
        appendLine("SocksPolicy accept 127.0.0.1/8")
        appendLine("SocksPolicy reject *")
        // 8118 is Privoxy's port and nothing here needs an HTTP proxy.
        appendLine("HTTPTunnelPort 0")
        appendLine()

        appendLine("# --- Client role -------------------------------------------------")
        appendLine("ClientOnly 1")
        // AvoidDiskWrites is deliberately not set. It exists to spare media
        // with a limited write life, and what it spares tor from writing
        // promptly is exactly what the next connect needs: the consensus and
        // descriptors it just fetched. A phone's storage is fine; a connect
        // that re-downloads the directory because the last run was told to
        // hold off writing it is not.
        appendLine("DormantCanceledByStartup 1")
        appendLine("DormantTimeoutEnabled 0")
        appendLine()

        appendLine("# --- Names -------------------------------------------------------")
        appendLine("DNSPort 127.0.0.1:${session.dnsPort}")
        appendLine("AutomapHostsOnResolve 1")
        appendLine("AutomapHostsSuffixes .")
        appendLine("VirtualAddrNetworkIPv4 $VIRTUAL_NETWORK_V4")
        appendLine("VirtualAddrNetworkIPv6 $VIRTUAL_NETWORK_V6")
        appendLine()

        appendLine("# --- Traffic shape ------------------------------------------------")
        // Netflow padding hides when a connection starts and ends; circuit
        // padding hides the shape of what is inside. Both default to on; they
        // are stated so a later battery optimisation cannot quietly drop them.
        // KeepalivePeriod is deliberately left alone: a short fixed keepalive
        // is the regular-interval marker traffic analysis looks for.
        appendLine("ConnectionPadding 1")
        appendLine("ReducedConnectionPadding 0")
        appendLine()

        appendLine("# --- Route --------------------------------------------------------")
        val opening = session.opening
        if (opening == null || opening.transport == Transport.DIRECT || opening.bridges.isEmpty()) {
            appendLine("UseBridges 0")
        } else {
            appendLine("UseBridges 1")
            opening.bridges.forEach { appendLine("Bridge ${it.raw}") }
        }
        appendLine()

        appendLine("# --- Circuits ----------------------------------------------------")
        // Timings for the route above. A later route sets its own over the
        // control port.
        tuning(opening?.transport ?: Transport.DIRECT).forEach { appendLine(it) }
        appendLine()

        appendLine("# --- Transports ---------------------------------------------------")
        // Declared up front for every transport that has a listener. tor does
        // not contact one until a bridge line names it, so listing them all
        // costs nothing and means switching rungs never needs a restart.
        session.plugins.forEach { (transport, port) ->
            appendLine("ClientTransportPlugin ${transport.torName} socks5 127.0.0.1:$port")
        }
        if (session.plugins.isEmpty()) {
            appendLine("# no transports available; only a direct connection can be tried")
        }
    }

    /**
     * Circuit timings that suit the route actually in use.
     *
     * These are set on every route change, and they matter more than they
     * look. Tor's defaults are calibrated for a direct connection: a circuit
     * has ten seconds to be built, the timeout is then *learned* from
     * observation, and a circuit stops accepting new streams after ten minutes.
     * Apply that to a path that goes through a volunteer's browser over WebRTC
     * and three things go wrong at once. Building takes longer than the
     * timeout, so tor abandons circuits it was about to finish. The learned
     * timeout is trained on those failures, so it tightens rather than
     * relaxes. And every ten minutes the next connection has to wait for a new
     * circuit over that same slow path — which is exactly the periodic stall a
     * Snowflake user notices without knowing where it comes from.
     *
     * So a broker-based transport gets a build timeout that reflects reality,
     * no adaptive learning, patience with individual streams, and half an hour
     * before circuits are rotated. The rotation interval is a real trade: a
     * circuit that lives longer links more of a session together. Thirty
     * minutes is the compromise Tor itself suggests for slow links, and it is
     * the difference between a tunnel that is usable and one that is not.
     */
    fun tuning(transport: Transport): List<String> = when (transport) {
        // Conjure belongs here for a different reason from the others: its
        // registration step is a fronted request to a station that can be under
        // load, so the first bytes routinely take tens of seconds even when
        // everything is working.
        Transport.SNOWFLAKE, Transport.MEEK, Transport.CONJURE -> listOf(
            "CircuitBuildTimeout 90",
            "LearnCircuitBuildTimeout 0",
            "CircuitStreamTimeout 60",
            "MaxCircuitDirtiness 1800",
        )

        // WebTunnel is ordinary TLS to a real host: slower than obfs4, but
        // nothing like a WebRTC hop.
        Transport.WEBTUNNEL -> listOf(
            "CircuitBuildTimeout 45",
            "LearnCircuitBuildTimeout 0",
            "CircuitStreamTimeout 30",
            "MaxCircuitDirtiness 1200",
        )

        Transport.DIRECT, Transport.OBFS4 -> listOf(
            "CircuitBuildTimeout 30",
            "LearnCircuitBuildTimeout 1",
            "CircuitStreamTimeout 0",
            "MaxCircuitDirtiness 900",
        )
    }

    /**
     * The smallest torrc that can still serve this app.
     *
     * Used as a fallback: if tor rejects the full configuration — one unknown
     * option is enough for it to refuse to start at all — the app retries with
     * this rather than reporting that the network is blocked when it is not.
     */
    fun minimal(session: Session): String = buildString {
        appendLine("# Generated by Veil (fallback configuration).")
        appendLine("SocksPort 127.0.0.1:${session.socksPort}")
        appendLine("DNSPort 127.0.0.1:${session.dnsPort}")
        appendLine("AutomapHostsOnResolve 1")
        appendLine("AutomapHostsSuffixes .")
        appendLine("VirtualAddrNetworkIPv4 $VIRTUAL_NETWORK_V4")
        session.plugins.forEach { (transport, port) ->
            appendLine("ClientTransportPlugin ${transport.torName} socks5 127.0.0.1:$port")
        }
        val opening = session.opening
        if (opening != null && opening.transport != Transport.DIRECT &&
            opening.bridges.isNotEmpty()
        ) {
            appendLine("UseBridges 1")
            opening.bridges.forEach { appendLine("Bridge ${it.raw}") }
        }
    }
}
