// There is no disk in the page: the only file the mock reads is the sample video.
import { Buffer } from "buffer";
import sample from "./sample-webm.js"; // generated by make-demo.mjs (base64)

const enoent = (p) => Object.assign(new Error("ENOENT: " + p), { code: "ENOENT" });
export function readFileSync(p) {
  if (String(p).endsWith("sample.webm")) return Buffer.from(sample, "base64");
  throw enoent(p);
}
export const statSync = (p) => { throw enoent(p); };
export const readdirSync = () => [];
export const existsSync = () => false;
export const createReadStream = (p) => { throw enoent(p); };
export default { readFileSync, statSync, readdirSync, existsSync, createReadStream };
